install:
	./gradlew clean install

run-dist:
	./build/install/app/bin/app

check-updates:
	./gradlew dependencyUpdates

report:
	./gradlew jacocoTestReport

lint:
	./gradlew checkstyleMain

build:
	./gradlew clean build

.PHONY: build